#              _                               ___      __         _     _        #
#     /\      | |                             | \ \    / /        (_)   | |       #
#    /  \   __| |_   ____ _ _ __   ___ ___  __| |\ \  / /_ _ _ __  _ ___| |__     #
#   / /\ \ / _` \ \ / / _` | '_ \ / __/ _ \/ _` | \ \/ / _` | '_ \| / __| '_ \    #
#  / ____ \ (_| |\ V / (_| | | | | (_|  __/ (_| |  \  / (_| | | | | \__ \ | | |   #
# /_/    \_\__,_| \_/ \__,_|_| |_|\___\___|\__,_|   \/ \__,_|_| |_|_|___/_| |_|   #
###################################################################################
# Version ${project.version} by quantiom

# Enable vanish on join
vanish-on-join: true

# Actions when players are vanished
# false = disabled, true = enabled
when-vanished:
  join-messages: false
  leave-messages: false
  send-messages: false
  break-blocks: false
  place-blocks: false
  interact: false
  attack-entities: false
  receive-damage-from-entities: false
  open-and-use-chests: false
  pick-up-items: false
  drop-items: false
  give-invisibility: true # Give an Invisibility II potion effect on vanish
  lose-hunger: false
  mob-targeting: false
  fly:
    enable: true
    keep-on-unvanish: false # The "keep-fly-on-unvanish" permission will override this if the player has that permission

# Permissions
permissions:
  vanish: "advancedvanish.vanish"
  help-command: "advancedvanish.help-command"
  reload-config-command: "advancedvanish.reload-config-command"
  priority-command: "advancedvanish.priority-command"
  list-command: "advancedvanish.list-command"
  status-command: "advancedvanish.status-command"
  keep-fly-on-unvanish: "advancedvanish.keep-fly"

# Fake join/leave messages
join-leave-messages:
  fake-join-message-on-unvanish:
    enable: false
    # Placeholders:
    #   %priority% - The player's vanish priority
    message: "&e%player-name% has joined the game"
  fake-leave-message-on-vanish:
    enable: false
    # Placeholders:
    #   %player-name% - The player's name
    message: "&e%player-name% has left the game."

# Hooks that will add support to other plugins
# Some hooks will not be enabled if the required plugin(s) are not found
hooks:
  # Hides players from Essentials commands such as: /list, /whois, etc...
  essentials: true
  # Requires ProtocolLib, removes vanished players from the server list (player count and players)
  server-list: true
  # Requires PlaceholderAPI, adds multiple placeholders which are configurable
  # in the placeholders section of this config
  placeholders: true
  # Requires ActionBarAPI, shows a message above the hotbar if a player is vanished
  # The configurable message is in the messages section below.
  actionbar: true
  # Requires DiscordSRV, sends a fake leave and join message when vanished/unvanished
  # and also requires the fake-join-message-on-unvanish / fake-leave-message-on-vanish to be
  # enabled (which is above)
  discordsrv: true
  # Requires Dynmap, will hide vanished players from the website
  dynmap: true
  # Requires LibsDisguises, removes disguises when vanished
  libsdisguises: true
  # Requires PlayerParticles, removes active particles when vanished
  playerparticles: true

# Requires the "placeholders" hook to be enabled
placeholders:
  # The placeholder identifier
  identifier: "advancedvanish"

  # All of these placeholders will be in the format of
  # %<identifier>_<placeholder>%
  # Ex: %advancedvanish_is_vanished%
  is-vanished: "is_vanished"
  vanished-players: "vanished_players"
  player-count: "player_count"

# Vanish Priority - Requires a supported permissions plugin to function
#
# Allows players with higher priorities to see vanished players from
# lower priorities without the lower priority players being able to see
# them, but they will still all be in vanish.
#
# Supported permissions plugins:
#   - LuckPerms (recommended)
#   - PermissionsEx
#   - bPermissions
#   - GroupManager
#
# To add the priority meta: (default is 0)
#   LuckPerms: /lp user/group <user|group> meta set meta.<meta-key> <priority-num>
#     (ex: /lp user quantiom meta set advancedvanish-priority 5)
#   bPermissions: (/user OR /group) meta <meta-key> <priority-num>
#     (ex: /user meta advancedvanish-priority 5)
#   PermissionsEx: /pex user/group <user|group> set <meta-key> <priority-num>
#     (ex: /pex user quantiom set advancedvanish-priority 5)
#   GroupManager: Add the permission <meta-key>.<priority-num>, and AdvancedVanish will use the highest number
#     (ex: /manuaddp quantiom advancedvanish-priority.5)
#
priority:
  enable: true
  meta-key: "advancedvanish-priority" # will be meta.advancedvanish-priority.<num>

# Messages that are sent to players.
# Set any message here to "" to display nothing.
messages:
  # Set/enable a prefix used before all messages
  prefix:
    enabled: true
    value: "&c[AdvancedVanish]&f "
  no-permission: "&cYou do not have permission to use this command."
  config-reloaded: "Successfully reloaded the config."
  vanish-on: "You are now in vanish."
  vanish-off: "You are no longer in vanish."
  cannot-chat-while-vanished: "You cannot chat while you are in vanish."
  cannot-place-blocks-while-vanished: "You cannot place blocks while you are in vanish."
  cannot-break-blocks-while-vanished: "You cannot break blocks while you are in vanish."
  cannot-attack-entities-while-vanished: "You cannot attack entities while you are in vanish."
  cannot-drop-items-while-vanished: "You cannot drop items while you are in vanish."
  opening-chest-silently: "Opening chest silently..."
  # Placeholders:
  #   %priority% - The player's vanish priority
  vanish-priority: "Your vanish priority is &c%priority%&f."
  not-using-vanish-priority: "You are not using vanish priority, it can be enabled in the config."
  # Placeholders:
  #   %vanished-players% - A list of vanished players, or "None"
  vanished-list: "Vanished players: &c%vanished-players%"
  # Placeholders:
  #   %target-name% - The target's username
  #   %vanish-status% - "On" or "Off"
  #   %vanish-status-word% - "vanished" or "not vanished"
  vanish-status-command: "&c%target-name%&f is currently &c%vanish-status-word%&f."
  action-bar: "&cYou are in vanish."
  disguise-removed-because-vanish: "Your disguise has been &cremoved&f because you are in vanish"

# Config version - Do NOT change this manually
config-version: 1